-- ============================================
-- 清理 Flowable 所有表
-- 用于重新初始化 Flowable 数据库
-- ============================================

SET FOREIGN_KEY_CHECKS = 0;

-- 删除所有 ACT_ 开头的表
DROP TABLE IF EXISTS ACT_GE_PROPERTY;
DROP TABLE IF EXISTS ACT_GE_BYTEARRAY;
DROP TABLE IF EXISTS ACT_RE_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_RE_MODEL;
DROP TABLE IF EXISTS ACT_RE_PROCDEF;
DROP TABLE IF EXISTS ACT_RU_EXECUTION;
DROP TABLE IF EXISTS ACT_RU_JOB;
DROP TABLE IF EXISTS ACT_RU_TIMER_JOB;
DROP TABLE IF EXISTS ACT_RU_SUSPENDED_JOB;
DROP TABLE IF EXISTS ACT_RU_DEADLETTER_JOB;
DROP TABLE IF EXISTS ACT_RU_TASK;
DROP TABLE IF EXISTS ACT_RU_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_RU_VARIABLE;
DROP TABLE IF EXISTS ACT_RU_EVENT_SUBSCR;
DROP TABLE IF EXISTS ACT_HI_PROCINST;
DROP TABLE IF EXISTS ACT_HI_ACTINST;
DROP TABLE IF EXISTS ACT_HI_TASKINST;
DROP TABLE IF EXISTS ACT_HI_VARINST;
DROP TABLE IF EXISTS ACT_HI_DETAIL;
DROP TABLE IF EXISTS ACT_HI_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_HI_COMMENT;
DROP TABLE IF EXISTS ACT_HI_ATTACHMENT;

-- 删除所有 FLW_ 开头的表
DROP TABLE IF EXISTS FLW_EVENT_DEPLOYMENT;
DROP TABLE IF EXISTS FLW_EVENT_RESOURCE;
DROP TABLE IF EXISTS FLW_EVENT_DEFINITION;
DROP TABLE IF EXISTS FLW_CHANNEL_DEFINITION;
DROP TABLE IF EXISTS FLW_EV_DATABASECHANGELOG;
DROP TABLE IF EXISTS FLW_EV_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS FLW_DATABASECHANGELOG;
DROP TABLE IF EXISTS FLW_DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS FLW_RU_BATCH;
DROP TABLE IF EXISTS FLW_RU_BATCH_PART;

SET FOREIGN_KEY_CHECKS = 1;