-- ============================================
-- Flowable 6.8.0 MySQL 数据库建表脚本
-- 官方参考: https://github.com/flowable/flowable-engine
-- ============================================

-- 通用引擎表
CREATE TABLE IF NOT EXISTS ACT_GE_PROPERTY (
    NAME_ VARCHAR(64) NOT NULL,
    VALUE_ VARCHAR(300),
    REV_ INT,
    PRIMARY KEY (NAME_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_GE_BYTEARRAY (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    NAME_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    BYTES_ LONGBLOB,
    GENERATED_ TINYINT,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 资源库表
CREATE TABLE IF NOT EXISTS ACT_RE_DEPLOYMENT (
    ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    KEY_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    DEPLOY_TIME_ DATETIME,
    DERIVED_FROM_ VARCHAR(64),
    DERIVED_FROM_ROOT_ VARCHAR(64),
    PARENT_DEPLOYMENT_ID_ VARCHAR(255),
    ENGINE_VERSION_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RE_MODEL (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    CREATE_TIME_ DATETIME,
    LAST_UPDATE_TIME_ DATETIME,
    VERSION_ INT,
    META_INFO_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    EDITOR_SOURCE_VALUE_ID_ VARCHAR(64),
    EDITOR_SOURCE_EXTRA_VALUE_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RE_PROCDEF (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    CATEGORY_ VARCHAR(255),
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255) NOT NULL,
    VERSION_ INT NOT NULL,
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(255),
    DGRM_RESOURCE_NAME_ VARCHAR(255),
    DESCRIPTION_ VARCHAR(255),
    HAS_START_FORM_KEY_ TINYINT,
    HAS_GRAPHICAL_NOTATION_ TINYINT,
    SUSPENSION_STATE_ INT,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    ENGINE_VERSION_ VARCHAR(255),
    DERIVED_FROM_ VARCHAR(64),
    DERIVED_FROM_ROOT_ VARCHAR(64),
    DERIVED_VERSION_ INT NOT NULL DEFAULT 0,
    DERIVED_TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_),
    UNIQUE KEY ACT_UNIQ_PROCDEF (KEY_, VERSION_, DERIVED_VERSION_, TENANT_ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 运行时表
CREATE TABLE IF NOT EXISTS ACT_RU_EXECUTION (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    PROC_INST_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    PARENT_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    SUPER_EXEC_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    IS_ACTIVE_ TINYINT,
    IS_CONCURRENT_ TINYINT,
    IS_SCOPE_ TINYINT,
    IS_EVENT_SCOPE_ TINYINT,
    IS_MI_ROOT_ TINYINT,
    SUSPENSION_STATE_ INT,
    CACHED_ENT_STATE_ INT,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    NAME_ VARCHAR(255),
    START_TIME_ DATETIME,
    START_USER_ID_ VARCHAR(255),
    LOCK_TIME_ DATETIME,
    IS_COUNT_ENABLED_ TINYINT,
    EVT_SUBSCR_COUNT_ INT,
    TASK_COUNT_ INT,
    JOB_COUNT_ INT,
    TIMER_JOB_COUNT_ INT,
    SUSP_JOB_COUNT_ INT,
    DEADLETTER_JOB_COUNT_ INT,
    VAR_COUNT_ INT,
    ID_LINK_COUNT_ INT,
    CALLBACK_ID_ VARCHAR(64),
    CALLBACK_TYPE_ VARCHAR(255),
    REFERENCE_ID_ VARCHAR(64),
    REFERENCE_TYPE_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ DATETIME,
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ TINYINT,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_TIMER_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ DATETIME,
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ TINYINT,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_SUSPENDED_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    TYPE_ VARCHAR(255) NOT NULL,
    EXCLUSIVE_ TINYINT,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_DEADLETTER_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    TYPE_ VARCHAR(255) NOT NULL,
    EXCLUSIVE_ TINYINT,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ DATETIME,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_TASK (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    TASK_DEF_KEY_ VARCHAR(255),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    DELEGATION_ VARCHAR(64),
    PRIORITY_ INT,
    CREATE_TIME_ DATETIME,
    DUE_DATE_ DATETIME,
    CATEGORY_ VARCHAR(255),
    SUSPENSION_STATE_ INT,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    FORM_KEY_ VARCHAR(255),
    CLAIM_TIME_ DATETIME,
    IS_COUNT_ENABLED_ TINYINT,
    VAR_COUNT_ INT,
    ID_LINK_COUNT_ INT,
    SUB_TASK_COUNT_ INT,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_IDENTITYLINK (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    GROUP_ID_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_VARIABLE (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    TYPE_ VARCHAR(255) NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    IS_BYTEARRAY_ TINYINT,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_RU_EVENT_SUBSCR (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    EVENT_TYPE_ VARCHAR(255) NOT NULL,
    EVENT_NAME_ VARCHAR(255),
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(255),
    CONFIGURATION_ VARCHAR(255),
    CREATED_ DATETIME NOT NULL,
    PROC_DEF_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 历史表
CREATE TABLE IF NOT EXISTS ACT_HI_PROCINST (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    PROC_INST_ID_ VARCHAR(64) NOT NULL,
    BUSINESS_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64) NOT NULL,
    START_TIME_ DATETIME NOT NULL,
    END_TIME_ DATETIME,
    DURATION_ BIGINT,
    START_USER_ID_ VARCHAR(255),
    START_ACT_ID_ VARCHAR(255),
    END_ACT_ID_ VARCHAR(255),
    SUPER_PROCESS_INSTANCE_ID_ VARCHAR(64),
    DELETE_REASON_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    NAME_ VARCHAR(255),
    CALLBACK_ID_ VARCHAR(64),
    CALLBACK_TYPE_ VARCHAR(255),
    REFERENCE_ID_ VARCHAR(64),
    REFERENCE_TYPE_ VARCHAR(255),
    PRIMARY KEY (ID_),
    UNIQUE KEY PROC_INST_ID_ (PROC_INST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_ACTINST (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    PROC_DEF_ID_ VARCHAR(64) NOT NULL,
    PROC_INST_ID_ VARCHAR(64) NOT NULL,
    EXECUTION_ID_ VARCHAR(64) NOT NULL,
    ACT_ID_ VARCHAR(255) NOT NULL,
    TASK_ID_ VARCHAR(64),
    CALL_PROC_INST_ID_ VARCHAR(64),
    CALL_CASE_INST_ID_ VARCHAR(64),
    ACT_NAME_ VARCHAR(255),
    ACT_TYPE_ VARCHAR(255) NOT NULL,
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ DATETIME NOT NULL,
    END_TIME_ DATETIME,
    TRANSACTION_ORDER_ INT,
    DURATION_ BIGINT,
    DELETE_REASON_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_TASKINST (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    PROC_DEF_ID_ VARCHAR(64),
    TASK_DEF_KEY_ VARCHAR(255),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ DATETIME NOT NULL,
    CLAIM_TIME_ DATETIME,
    END_TIME_ DATETIME,
    DURATION_ BIGINT,
    DELETE_REASON_ VARCHAR(4000),
    PRIORITY_ INT,
    DUE_DATE_ DATETIME,
    FORM_KEY_ VARCHAR(255),
    CATEGORY_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_VARINST (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    NAME_ VARCHAR(255) NOT NULL,
    VAR_TYPE_ VARCHAR(100),
    SCOPE_ID_ VARCHAR(64),
    SUB_SCOPE_ID_ VARCHAR(64),
    SCOPE_TYPE_ VARCHAR(255),
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    CREATE_TIME_ DATETIME,
    LAST_UPDATED_TIME_ DATETIME,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_DETAIL (
    ID_ VARCHAR(64) NOT NULL,
    TYPE_ VARCHAR(255) NOT NULL,
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    ACT_INST_ID_ VARCHAR(64),
    NAME_ VARCHAR(255) NOT NULL,
    VAR_TYPE_ VARCHAR(255),
    REV_ INT,
    TIME_ DATETIME NOT NULL,
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_IDENTITYLINK (
    ID_ VARCHAR(64) NOT NULL,
    GROUP_ID_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    SCOPE_ID_ VARCHAR(64),
    SCOPE_TYPE_ VARCHAR(255),
    SCOPE_DEFINITION_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_COMMENT (
    ID_ VARCHAR(64) NOT NULL,
    TYPE_ VARCHAR(255),
    TIME_ DATETIME NOT NULL,
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTION_ VARCHAR(255),
    MESSAGE_ VARCHAR(4000),
    FULL_MSG_ LONGBLOB,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ACT_HI_ATTACHMENT (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INT,
    USER_ID_ VARCHAR(255),
    NAME_ VARCHAR(255),
    DESCRIPTION_ VARCHAR(4000),
    TYPE_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    URL_ VARCHAR(4000),
    CONTENT_ID_ VARCHAR(64),
    TIME_ DATETIME,
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 插入版本信息
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.version', '6.8.0.0', 1) ON DUPLICATE KEY UPDATE VALUE_ = '6.8.0.0';
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.history', 'create(6.8.0.0)', 1) ON DUPLICATE KEY UPDATE VALUE_ = 'create(6.8.0.0)';
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('common.schema.version', '6.8.0.0', 1) ON DUPLICATE KEY UPDATE VALUE_ = '6.8.0.0';
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('common.schema.history', 'create(6.8.0.0)', 1) ON DUPLICATE KEY UPDATE VALUE_ = 'create(6.8.0.0)';
